
export const  FIELDS=[
    {field:'id', headerName:'ID',type:'text', required:false, onChange:'', onBlur:'', group:'Date', category:'', input:'input', source:'', hide:true, format:'big'},
    {field:'email', headerName:'E-mail:',type:'text', required:true,onChange:'', onBlur:'',group:'Date', category:'', input:'input', source:'', hide:false, format:'big'},
    {field:'password', headerName:'Parola:',type:'password', required:false, onChange:'', onBlur:'',group:'Parola', category:'',input:'input', source:'', hide:false, format:'big'},
    {field:'role.id', headerName:'Rol:',type:'text', required:true, onChange:'', onBlur:'',group:'Date', category:'',input:'select', source:'', hide:false, format:'big'},
    {field:'blocked', headerName:'Blocat:',type:'checkbox', required:false, onChange:'', onBlur:'',group:'Date', category:'',input:'checkbox',source:'', hide:false, format:'big'},
    {field:'provider', headerName:'Provider:',type:'text', required:false, onChange:'', onBlur:'',group:'Date', category:'',input:'input',source:'', hide:true, format:'big'},
    {field:'Denumire', headerName:'Denumire:',type:'text', required:true, onChange:'', onBlur:'',group:'Date', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'CodFiscal', headerName:'Cod fiscal:',type:'text', required:false, onChange:'', onBlur:'',group:'Date', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'AtributFiscal', headerName:'Atribut fiscal:',type:'text', required:false, value:'',onChange:'', onBlur:'',group:'Date', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'Oras', headerName:'Oras:',type:'text', required:true, onChange:'', onBlur:'',group:'Date', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'Adresa', headerName:'Adresa:',type:'text', required:true, onChange:'', onBlur:'',group:'Date', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'Judet', headerName:'Judet:',type:'text', required:true, onChange:'', onBlur:'',group:'Date', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'Cont', headerName:'Cont:',type:'text', required:false, onChange:'', onBlur:'',group:'Date', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'Banca', headerName:'Banca:',type:'text', required:false, onChange:'', onBlur:'',group:'Date', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'Observatii', headerName:'Observatii:',type:'text', required:false,onChange:'', onBlur:'',group:'Date', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'DiscountJV', headerName:'Jaluzele verticale:',type:'number', required:false, onChange:'', onBlur:'',group:'Discounturi', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'DiscountRO', headerName:'Rolete textile:',type:'number', required:false, onChange:'', onBlur:'',group:'Discounturi', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'DiscountRE', headerName:'Rulouri exterioare:',type:'number', required:false, onChange:'', onBlur:'',group:'Discounturi', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'DiscountUG', headerName:'Usi de garaj:',type:'number', required:false, onChange:'', onBlur:'',group:'Discounturi', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'DiscountPI', headerName:'Plase insecte:',type:'number', required:false, onChange:'', onBlur:'',group:'Discounturi', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'DiscountJO', headerName:'Jaluzele orizontale:',type:'number', required:false, onChange:'', onBlur:'',group:'Discounturi', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'DiscountTR', headerName:'Rul. transparente:',type:'number', required:false, onChange:'', onBlur:'',group:'Discounturi', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'DiscountCO', headerName:'Componente:',type:'number', required:false, onChange:'', onBlur:'',group:'Discounturi', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'DiscountSR', headerName:'Servicii:',type:'number', required:false, onChange:'', onBlur:'',group:'Discounturi', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'AdaosJV', headerName:'Jaluzele verticale:',type:'number', required:false, onChange:'', onBlur:'',group:'Adaosuri', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'AdaosRO', headerName:'Rolete textile:',type:'number', required:false, onChange:'', onBlur:'',group:'Adaosuri', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'AdaosRE', headerName:'Rulouri exterioare:',type:'number', required:false, onChange:'', onBlur:'',group:'Adaosuri', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'AdaosUG', headerName:'Usi de garaj:',type:'number', required:false, onChange:'', onBlur:'',group:'Adaosuri', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'AdaosPI', headerName:'Plase Insecte:',type:'number', required:false, onChange:'', onBlur:'',group:'Adaosuri', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'AdaosJO', headerName:'Jaluzele orizontale:',type:'number', required:false, onChange:'', onBlur:'',group:'Adaosuri', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'AdaosTR', headerName:'Rul. transparente:',type:'number', required:false, onChange:'', onBlur:'',group:'Adaosuri', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'AdaosCO', headerName:'Componente:',type:'number', required:false, onChange:'', onBlur:'',group:'Adaosuri', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'AdaosSR', headerName:'Servicii:',type:'number', required:false, onChange:'', onBlur:'',group:'Adaosuri', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'Mesaj', headerName:'Mesaj',type:'text', required:false, onChange:'', onBlur:'',group:'', category:'',input:'input',source:'', hide:false, format:'small'},
    {field:'CFG1', headerName:'CFG1',type:'text', required:false, onChange:'', onBlur:'',group:'', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'CFG2', headerName:'CFG2',type:'text', required:false, onChange:'', onBlur:'',group:'', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'CFG3', headerName:'CFG3',type:'text', required:false, onChange:'', onBlur:'',group:'', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'idDevco', headerName:'Id Devco',type:'text', required:false, onChange:'', onBlur:'',group:'', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'confirmareParola', headerName:'Confirmare parola',type:'password', required:false, onChange:'', onBlur:'',group:'Parola', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'createdBy', headerName:'Creat de',type:'text', required:false, onChange:'', onBlur:'',group:'Jurnal', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'created_at', headerName:'Creat la:',type:'text', required:false, onChange:'', onBlur:'',group:'Jurnal', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'updatedBy', headerName:'Modificat de',type:'text', required:false, onChange:'', onBlur:'',group:'Jurnal', category:'',input:'input',source:'', hide:false, format:'big'},
    {field:'fotografie.url', headerName:'Fotografie:',type:'file', required:false, onChange:'', onBlur:'',group:'Fotografie', category:'',input:'media',source:'', hide:false,format:'big'},
] 
